services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  app:
    build: .
    container_name: linebot-file
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
